---
- hosts: localhost
  become: true
  gather_facts: true
  tasks:
    - name: Update Ubuntu package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Java
      apt:
        name: openjdk-11-jre
        state: present

    - name: Download Apache Maven
      get_url:
        url: https://dlcdn.apache.org/maven/maven-3/3.9.5/binaries/apache-maven-3.9.5-bin.tar.gz
        dest: /opt

    - name: Extract Apache Maven
      unarchive:
        src: /opt/apache-maven-3.9.5-bin.tar.gz
        dest: /opt
        remote_src: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service on boot
      service:
        name: docker
        enabled: yes

    - name: Give 777 permission on /var/run/docker.sock
      file:
        path: /var/run/docker.sock
        state: file
        mode: '777'

    - name: Download kubectl
      get_url:
        url: https://s3.us-west-2.amazonaws.com/amazon-eks/1.24.9/2023-01-11/bin/linux/amd64/kubectl
        dest: /usr/local/bin
        mode: '0755'

    - name: Download get_helm.sh
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '0700'

    - name: Execute get_helm.sh
      command: /tmp/get_helm.sh

    - name: Download AWS CLI
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip

    - name: Install Unzip
      apt:
        name: unzip
        state: present

    - name: Unzip AWS CLI
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp
        remote_src: yes

    - name: Install AWS CLI
      command: /tmp/aws/install --update

    - name: Update kubeconfig
      shell:
        cmd: "aws eks update-kubeconfig --region us-east-1 --name demo-eks-01"
        executable: /bin/bash
